config/routes.rb
Rails.application.routes.draw do

  root to: 'dashboard#show'

  resource :slack_authentication, only: [:show] do
    collection do
      get 'callback'
    end
  end

  resources :menus, only: [:index, :new, :create]

  resources :menu_blocs, only: [:create]

  namespace :api do
    scope module: :v1 do
      resource :message_action, only: [:create]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :user
  belongs_to :option
end

app/models/meal.rb
class Meal < ApplicationRecord
  has_many :options
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :options
  has_many :menu_bloc_memberships
  has_many :menu_blocs, through: :menu_bloc_memberships
end

app/models/menu_bloc.rb
class MenuBloc < ApplicationRecord
  has_many :menu_bloc_memberships
  has_many :menus, through: :menu_bloc_memberships
end

app/models/menu_bloc_membership.rb
class MenuBlocMembership < ApplicationRecord
  belongs_to :menu
  belongs_to :menu_bloc
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :menu
  belongs_to :meal
end

app/models/slack_team.rb
class SlackTeam < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/api/v1/api_base_controller.rb
class Api::V1::ApiBaseController < ApplicationController
  protect_from_forgery with: :null_session
end

app/controllers/api/v1/message_actions_controller.rb
class Api::V1::MessageActionsController < Api::V1::ApiBaseController

  def create
    # quickly check that a choice was submitted - if so
    MessageReceivedJob.perform_later(JSON.parse(params[:payload]))
    render json: "That's great, thanks", status: 200
    # if not, rerender the message with some extra text
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show
  end

end

app/controllers/frontend_base_controller.rb
class FrontendBaseController < ApplicationController
  protect_from_forgery with: :exception
end

app/controllers/menu_blocs_controller.rb
class MenuBlocsController < FrontendBaseController

  def create
    MenuBlocs::Create.new(params).perform
    redirect_to menus_path
  end

end

app/controllers/menus_controller.rb
class MenusController < FrontendBaseController

  def new
    @form = MenuForm.new(Menu.new(date: Date.current)).prepopulate!
  end

  def index
    @menus = Menu.all
  end

  def create
    @form = MenuForm.new(Menu.new)
    if @form.validate(params[:menu]) && @form.save
      redirect_to menus_path
    else
      render :new
    end
  end

end

app/controllers/slack_authentications_controller.rb
class SlackAuthenticationsController < FrontendBaseController

  def show
    scope = 'scope=chat:write:bot,users:read'
    client_id = 'client_id=' + ENV['SLACK_ID']
    redirect_uri = 'redirect_uri=' + callback_slack_authentication_url
    query_string = [scope, client_id, redirect_uri].join('&')

    redirect_to 'https://slack.com/oauth/authorize?' + query_string
  end

  def callback
    if team = SlackClient.link_account(authorization_code: params['code'], redirect_uri: callback_slack_authentication_url)
      flash[:notice] = "Successfully linked #{team.team_name}"
    else
      flash[:error] = 'Unable to link Slack Team. Please try again.'
    end
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/dashboard/show.html.erb
A user is logged in at this point

<%= link_to 'Link your Slack Team', slack_authentication_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>
  <%= render "css_overrides" %>
</body>
</html>

app/views/menus/_option.html.erb
<div class='nested-fields'>
  <%= f.label :meal %>
  <%= f.fields_for :meal do |mf| %>
    <%= mf.label :name %>
    <%= mf.text_field :name %>
    <%= mf.label :description %>
    <%= mf.text_area :description %>
  <% end %>
  <%= link_to_remove_association 'Remove', f %>
</div>

app/views/menus/index.html.erb
<%= link_to 'Add New Menu', new_menu_path %>

<% unless @menus.blank? %>
  <%= form_for :menu_block, url: menu_blocs_path do |f| %>
    <ul>
      <% @menus.each do |menu| %>
        <li>
          <%= menu.date %>
          <%= f.check_box menu.id %>
        </li>
      <% end %>
    </ul>
    <%= f.submit 'Send out menus' %>
  <% end %>

<% end %>

app/views/menus/new.html.erb
<%= form_for @form, url: menus_path do |f| %>
  <%= f.label :date %>
  <%= f.date_field :date %>

  <%= f.label :options %>
  <div id='options'>
    <%= f.fields_for :options do |of| %>
      <%= render 'option', f: of %>
    <% end %>
    <%= link_to_add_association 'Add', f, :options, partial: 'option', force_non_association_create: true %>
  </div>

  <%= f.submit 'Create Menu' %>
<% end %>